### ISSUE TITLE
[Suggestion] Be able to sell items

### ISSUE THREAD

**Issue by NoltoxGit** [byteful/NightMarket#5]
Hello,
The plugin is great, but it's missing a feature. Would it be possible to add a configuration allowing you to switch between buying and selling items ?

Thank you so much !

**Comment by byteful** [comment]
I don't think I will be adding this sorry. I feel the sole purpose of this plugin is to provide randomized shops for each player that they can purchase "rare" items from, and I don't think adding the ability to sell items would fit that. It would also require some redesign in the plugin, and I don't think it is worth it right now, sorry.
